apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongotest
  labels:
    app: mongodb
spec:
#  type: ClusterIP
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017           # internal cluster port
      targetPort: 27017     # container port
      nodePort: 32017       # external port on the Node
      protocol: TCP
