version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fastapi_network

  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - celery
    networks:
      - fastapi_network

  celery:
    build: .
    container_name: celery
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis
    networks:
      - fastapi_network

  flower:
    build: .
    container_name: flower
    command: celery -A celery_worker flower --port=5555 --broker=redis://redis:6379/0 --result-backend=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    networks:
      - fastapi_network

networks:
    fastapi_network:
        driver: bridge
